(require 'seq)

(load! "~/.emacs.d/project.el")

(defun display-eirene-banner-graphics ()
  (insert " _____                               \n")
  (insert "|  ___)                              \n")
  (insert "| |_    _    ___   _ ")
  (insert-char #x200b) (insert "_")
  (insert-char #x200b) (insert "_   _  ")
  (insert-char #x200b) (insert "_")
  (insert-char #x200b) (insert "_ _ __ \n")
  (insert "|  _)  | |  / _ \\ | '_ \\ | |/ /| '_ \\ \n")
  (insert "| |___ | | | |_) )| | | || / / | | | |\n")
  (insert "|_____) \\_)|  __/ |_| | ||__/  |_| | |\n")
  (insert "           | |        | |          | |\n")
  (insert "           |")
  (insert-char #x200b)
  (insert "_|        |_|          |_|\n"))

(defun display-eirene-banner-terminal ()
  (insert "#+BEGIN_SRC\n")
  (insert " _____                               \n")
  (insert "|  ___)                              \n")
  (insert "| |_    _    ___   _ __   _  __ _ __ \n")
  (insert "|  _)  | |  / _ \\ | '_ \\ | |/ /| '_ \\ \n")
  (insert "| |___ | | | |_) )| | | || / / | | | |\n")
  (insert "|_____) \\_)|  __/ |_| | ||__/  |_| | |\n")
  (insert "           | |        | |          | |\n")
  (insert "           |_|        |_|          |_|\n")
  (insert "#+END_SRC\n"))

(defun display-projects ()
  (let ((projects '()))
    (dolist (alist *projects*)
      (push (car alist) projects))
    (when projects
      (insert "Projects: \n\n")
      (let ((index 1))
	(dolist (project projects)
	  (insert (format "%s - %s \n" index project))
	  (setq index (+ index 1)))))))

(defun display-recent-files ()
  (recentf-mode)
  (let ((recent-files (seq-take recentf-list 7))
	(index 1))
    (insert "Recent Files: \n\n")
    (dolist (path recent-files)
      (insert (format "%s - [[%s]] \n" index path))
      (setq index (+ index 1)))
    (insert "\n")))

(defun display-keybindings ()
  (let ((bindings '()))
    (push
     `("find-file" . ,(substitute-command-keys "\\[counsel-find-file]"))
     bindings)
    (push
     `("M-x" . ,(substitute-command-keys "\\[counsel-M-x]"))
     bindings)
    (insert "Key Bindings: \n\n")
    (insert "| key | binding |\n")
    (insert "|-----+---------|\n")
    (dolist (key bindings)
      (insert (format "|%s| \"%s\"|\n" (car key) (cdr key))))
    (insert "|-----+--------|")
    (org-table-align)
    (insert "\n\n")))




(defun eirene-splash (load-time)
  (switch-to-buffer "*Eirene Splash*")
  (let ((start (point-min))
	(end   (point-max)))
    (org-mode)
    (kill-region start end)
    (insert "\n\n\n")
    (display-eirene-banner-terminal)
    (insert "\n\n\n")
    (insert (format "Load time: %s" load-time))
    (insert "\n\n\n")
    (display-keybindings)
    (insert "\n")
    (display-projects)
    (insert "\n")
    (display-recent-files)
    (goto-char start)
    (read-only-mode)
    (when (display-graphic-p)
      (local-set-key (kbd "<return>") #'org-open-at-point))))
